included:
  - Sources

disabled_rules:
  - cyclomatic_complexity
  - file_length
  - function_body_length
  - identifier_name
  - large_tuple
  - line_length
  - todo

opt_in_rules:
  - empty_count
  - file_header
  - force_unwrapping

file_header:
  required_pattern: |
    //
    // SWIFTLINT_CURRENT_FILENAME
    // ColorWell
    //

trailing_comma:
  mandatory_comma: true

type_name:
  allowed_symbols: ["_"]
